# language: node_js
# node_js:
#   - v16.11.0
# install:
#   - npm install
#   - npm run build
# script:
#   - chmod u+x deploy.sh
#   - bash ./deploy.sh
# cache:
#   directories:
#     - node_modules
# branch: master