# This is a basic workflow to help you get started with Actions

name: Deploy gh-pages

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [master]

jobs:
  build:
    name: Code Lint & Test Build
    env:
      MY_SECRET   : ${{secrets.GITHUB_TOKEN}}

    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.11.0]

    steps:
      - name: Checkout ğŸ›
        uses: actions/checkout@master

      - name: Install dependencies ğŸ‘¨ğŸ»â€ğŸ’»
        run: npm install

      - name: test build front end project ğŸ‘¨ğŸ»â€ğŸ’»
        run: npm run build

      - name: push
        run:  |
          echo ${{secrets.GITHUB_TOKEN}} | sudo -S chown -R $USER:$USER .vuepress/dist
          cd .vuepress/dist
          git init
          git config --global user.email "s8710606@gmail.com"
          git config --global user.name "EasonChang0115"
          git remote add origin https://${MY_SECRET}@github.com/EasonChang0115/EasonChang0115.github.io.git
          git add .
          git commit -m "deploy to Github pages"
          git push origin master -f

