# This is a basic workflow to help you get started with Actions

name: Deploy gh-pages

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [master]

jobs:
  build:
    name: Code Lint & Test Build
    env:
      MY_SECRET   : ${{secrets.commit_secret}}
      PUBLISH_DIR : .vuepress/dist
    
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.11.0]

    steps:
      - name: Checkout ğŸ›
        uses: actions/checkout@master

      - name: Install dependencies ğŸ‘¨ğŸ»â€ğŸ’»
        run: npm install

      - name: test build front end project ğŸ‘¨ğŸ»â€ğŸ’»
        run: npm run build

      - name: Commit files
        run: ./deploy.sh
        shell: bash
